### ISSUE TITLE
ChEBI records not properly associated with other documents

### ISSUE THREAD

**Issue by zcqian** [biothings/mychem.info#86]
It seems that some ChEBI aren't properly indexed, for instance `CHEBI:81931`, `CHEBI:63038`, etc. (both listed in their entity of the month), are not indexed with the respective InChIKey as its `_id`.

In this case, users cannot find related data except for ChEBI when using something like https://mychem.info/v1/chem/CHEBI%3A81931 (e.g. no PubChem info), but all other records are shown when using https://mychem.info/v1/chem/CID%3A61021

**Comment by kevinxin90** [comment]
@newgene 

Currently, seems all CHEBI records are not properly merged with other MyChem docs. The reason is in current data transform module for MyChem.info, all edges from CHEBI ID are removed. See line 67-76 in the [keylook.py file](https://github.com/biothings/mychem.info/blob/master/src/hub/datatransform/keylookup.py#L67).

And I was looking at the commit history of the Keylookup.py file, in [this commit](https://github.com/biothings/mychem.info/commit/ad7aa75665fcbf68febd4936539d8e8f54e92d5a#diff-d2a76563d346b0e5fdc5a5fa33022f528747a97cce61b85d511267166741374b), @sirloon  removed/commented out all edges from CHEBI. I believe that's the reason why CHEBI docs are not merged correctly with other documents. I don't recall any discussion that lead to this decision. Do you recall any? @newgene

**Comment by newgene** [comment]
@kevinxin90 don't remember any reason for commenting out chebi edges. Let's add them back and reload CHEBI.

**Comment by kevinxin90** [comment]
Fixed in https://github.com/biothings/mychem.info/pull/87/commits/838a794194e193c8fd478384fb38357ca333ebe4
