### ISSUE TITLE
Value consistency

### ISSUE THREAD

**Issue by kevinxin90** [biothings/mychem.info#9]
Pubchem ID in mychem.info should have unified name
"pharmgkb.pubchem_compound": "132971",
"pubchem.cid": "CID132971"

**Comment by greg-k-taylor** [comment]
I can see two problems with the example data entries posted above.

I agree that idealy we should have a unified name between datasets (in this case, 'pharmgkb and pubchem').  We would need to change the field names as appropriate - I would propose "pharmgkb.pubchem_id" and "pubchem.pubchem_id".  However, changing the field name now presents a problem in that any software that currently depends on the field name will break.  To address this, we could add the additional field names instead of changing them so that we are backwards compatible.

There is an additional problem with the example posted above in that the data values of two fields are inconsistent as well.  The values are "CID132971" and "132971".  I propose that also make the two values agree to the pubchem identifier of "CID132971" in the new fields.

Let me know what you think.

**Comment by kevinxin90** [comment]
Fixed in 47c4db64ec047c362465bec13976a430bb144d5e
